### ISSUE TITLE
Camera Movement

### ISSUE THREAD

**Issue by Exonoesis** [Exonoesis/Helping-Hand#2]
Current Tasks
- [ ] Camera follows player

**Comment by divark** [comment]
There may be an issue with our current camera approach when it comes to the two queries. According to [this post](https://github.com/bevyengine/bevy/discussions/2619), we should include a Without filter statement when asking for the Camera so that Rust doesn't get confused about a possible Component Bundle sharing both a Player and a Camera:
```rust
pub fn move_camera(
    player_query: Query<&Transform, (With<Player>, Changed<Transform>)>,
    mut camera_query: Query<&mut Transform, (With<Camera>, Without<Player>)>
)
```
